name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Satria Gucci"
          git config --global user.email "fngevnthppv@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote set-url gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crunchquest/CrunchQuest.git
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crunchquest/CrunchQuest.git

      - name: Pull latest changes from GitLab
        run: |
          git pull gitlab main --rebase || true  # Add || true to prevent the job from failing if no changes

      - name: Push to GitLab
        run: |
          git push gitlab main

