name: Sync to GitLab

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      - name: Set up Git
        run: |
          git config --global user.name "Satria Gucci"
          git config --global user.email "fngevnthppv@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crunchquest/CrunchQuest.git

      - name: Pull latest changes from GitLab
        run: |
          git pull --rebase gitlab main || {
            echo "Rebase failed; attempting to merge."
            git merge --strategy-option theirs gitlab/main -m "Merge GitLab changes into main, favoring remote changes"
          }

      - name: Push to GitLab
        run: |
          git push gitlab main
