name: Sync to GitLab

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Satria Gucci"
          git config --global user.email "fngevnthppv@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crunchquest/CrunchQuest.git

      - name: Fetch and merge changes from GitLab
        run: |
          git fetch gitlab main
          git checkout main
          git pull --rebase gitlab main

      - name: Push to GitLab
        run: |
          git push gitlab main
