name: Sync to GitLab

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Satria Gucci"
          git config --global user.email "fngevnthppv@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crunchquest/CrunchQuest.git

      - name: Fetch and merge changes from GitLab
        run: |
          git fetch gitlab main
          git checkout main
          # Attempt to rebase, if conflict happens, use ours strategy
          git rebase gitlab/main || {
            git rebase --abort
            git merge -s ours --allow-unrelated-histories gitlab/main
            git add .github/workflows/sync_to_gitlab.yml
            git commit -m "Resolve merge conflict by keeping local changes"
          }

      - name: Push to GitLab
        run: |
          git push gitlab main --force-with-lease
