name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Satria Gucci"
          git config --global user.email "fngevnthppv@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:glpat-EsAHKM6bwZFzhP7kwmj3@gitlab.com/crunchquest/CrunchQuest.git

      - name: Pull latest changes from GitLab
        run: |
          git fetch gitlab main
          git checkout main
          # Attempt rebase and resolve conflicts automatically by keeping our changes
          git rebase gitlab/main || {
          git rebase --abort
          git merge -s ours gitlab/main
          }

      - name: Push to GitLab
        run: |
          git push gitlab main --force-with-lease  # Use --force-with-lease to avoid overwriting remote changes unexpectedly


