name: Sync to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/Satriagucci/crunchquest/CrunchQuest.git
          git push gitlab main  # Change to your target branch
